name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT }}'

    - name: Build and push image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/document-management:$GITHUB_SHA

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: document-management
        image: gcr.io/${{ secrets.GCP_PROJECT }}/document-management:$GITHUB_SHA
        region: '${{ secrets.GCP_REGION }}'
        allow_unauthenticated: true
